### ISSUE TITLE
metadata key error from dispatch

### ISSUE THREAD

**Issue by jiale0402** [walkway-project/utils#47]
```Writing Metadata
Traceback (most recent call last):
  File "/home/lemat/catalyst/catalyst/grail/grail/features/dispatch.py", line 205, in <module>
    dispatch(verbose = True)
  File "/home/lemat/catalyst/catalyst/grail/grail/features/dispatch.py", line 81, in dispatch
    compute_feature(featureName = item,
  File "/home/lemat/catalyst/catalyst/grail/grail/features/dispatch.py", line 176, in compute_feature
    generator.read_metadata(catalystBase)
  File "/home/lemat/catalyst/catalyst/utils/utils/DataFetching/metadata/metadata.py", line 70, in read_metadata
    self.lookback = mdDict[self.LOOKBACK_KEY]
                    ~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'lookback'
```

**Comment by echavemann** [comment]
This is caused by Utils/Download not providing a default look back value. We should just set this to 0.
